config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :sports, only: [:index, :new, :create]
  resources :products do
    resources :bookings, only: [:new, :create]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :bookings, only: [:index, :show]
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :sport
  has_many :bookings
  has_one_attached :photo
  include PgSearch::Model
  pg_search_scope :products_search,
  against: [ :name, :description ],
  using: {
    tsearch: { prefix: true }
  }
end

app/models/sport.rb
class Sport < ApplicationRecord
  has_many :products
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products
  has_many :bookings

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit::Authorization
  # Para pundit:
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :location])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :location])
  end


  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = policy_scope(Booking)
  end

  def show
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def new
    @product = Product.find(params[:product_id])
    @booking = Booking.new
    authorize @booking
  end

  def create
    @product = Product.find(params[:product_id])
    @booking = Booking.new(booking_params)
    @booking.user_id = current_user.id
    @booking.product_id = @product.id
    @days = (@booking.end_date - @booking.start_date).to_i
    @booking.booking_price = @days * @product.price
    authorize @booking
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def booking_params
    params.require(:booking).permit(
      :start_date, :end_date
    )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]


  def index
    #@products = policy_scope(Product)
    #@sports = Sport.all
    if params[:query].present?
      @products = policy_scope(Product.products_search(params[:query]))
    else
      @products = policy_scope(Product)
    end
  end

  def new
    @product = Product.new
    authorize @product
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user
    authorize @product
    if @product.save!
      redirect_to products_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @product = Product.find(params[:id])
    @marker = [{ lat: @product.user.latitude, lng: @product.user.longitude }]
    authorize @product
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    if @product.save
      redirect_to products_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    # No need for app/views/restaurants/destroy.html.erb redirect_to restaurants_path, status: :see_other
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price, :sport_id, :photo)
  end
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  def index
    @sports = policy_scope(Sport)
  end

  def new
    @sport = Sport.new
  end

  def create
    @sport = Sport.new(sport_params)
    if @sport.save
      flash[:notice] = "Your sport was successfully created"
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def sport_params
    params.require(:sport).permit(
      :name
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container">
<br>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Producto</th>
        <th>Descripción</th>
        <th>Inicio alquiler</th>
        <th>Fin alquiler</th>
        <th>Precio</th>
        <th> Mostrar </th>
      </tr>
    </thead>
    <tbody>
      <% @bookings.each do |b| %>
        <tr>
         <!-- <td><%= cl_image_tag(b.product.photo.key, crop: :fill) %></td> -->
          <td><%= b.product.name%></td>
          <td><%= b.product.description%></td>
          <td><%= b.start_date.strftime("%d/%m/%Y") %></td>
          <td><%= b.end_date.strftime("%d/%m/%Y")%></td>
          <td><%= b.booking_price%></td>
          <td><%= link_to 'Show', booking_path(b) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/bookings/new.html.erb
<div>
  <div class="bg-success p-2 text-dark bg-opacity-25">
    <div class="bg-body card mx-2 my-2 p-5 shadow">
      <div class="card-header shadow-lg">
        <h1>Agenda tu reserva para:<%= @product.name %></h1>
      </div>
      <div class="card-header shadow-lg my-5">
        <%= simple_form_for [@product, @booking] do |f| %>
          <%= f.input :start_date %>
          <%= f.input :end_date %>
          <%=f.submit 'Submit booking',class:'btn btn-outline-success rounded-pill'%>
          <%# <%= link_to "Ver Resumen del booking", booking_path, class: "nav-link"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="card text-center">
  <div class="card-header">
     Airbnbsport <i class="fas fa-heart danger"></i>
  </div>

      <div class="card-body">
        <h5 class="card-title">Special title treatment</h5>
        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
        <div class="mt-3 mx-4">
          <button type="button" class="btn btn-outline-success text-primary text-opacity-75"><%= link_to "Arrienda tu propio equipo!", new_product_path, class: "nav-link" %> </button>
        </div>
      </div>


    <div class="card-footer w-100">
      <div class="footer-links">
        <div class="mx-auto">
          <a href="#"><i class="fab fa-github"></i></a>
          <a href="#"><i class="fab fa-instagram"></i></a>
          <a href="#"><i class="fab fa-facebook"></i></a>
          <a href="#"><i class="fab fa-twitter"></i></a>
          <a href="#"><i class="fab fa-linkedin"></i></a>
        </div>
      </div>
    </div>
</div>

app/views/bookings/show.html.erb
<div class="card col-12 mb-3 m-3" style="max-width: 10000px;">
  <div class="row g-0">
    <div class="col-7 md-4">
      <%= cl_image_tag(@booking.product.photo.key, crop: :fill, width: 450) %>
    </div>
    <div class="col-5 md-8 d-flex align-items-center">
      <div class="card-body col-5" >
        <h2 class="card-title"><%= @booking.product.name %></h2>
        <p class="card-text">Precio Reserva: <%=@booking.booking_price %> USD</p>
        <p class="card-text">Detalles producto: <%=@booking.product.description %></p>
        <p class="card-text"><small class="text-strong">Desde: <%= @booking.start_date %> hasta: <%= @booking.end_date %></small></p>
        <p class="card-text"><small class="text-strong"></small></p>
        <p><small><button type="button" class="btn btn-light">Contacta al dueño **nicetohave: <%= @booking.product.user.email %></button></small></p>
        <p><small><button type="button" class="btn btn-light"><%= link_to "Volver a mis reservas", bookings_path, class: "nav-link" %></button></small></p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airbnbsport</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
   <!--<script src="https://kit.fontawesome.com/29491137f1.js" crossorigin="anonymous"></script>-->
  </head>

  <body>
   <%= render "shared/navbar" %>
    <%= yield %>
   <%= render "shared/flashes" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-8  mx-auto">
      <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
        <div class= "text-carousel">
          <h1>     Find your equipments here </h1>
        </div>

        <div class="carousel-inner">
          <div class="carousel-item active">
            <!-- <img src="<%=image_tag 'baseball.jpeg'%>" heigth=300px alt="Baseball image">-->
            <%=image_tag "baseball.jpeg", class: "d-block w-100"%>
          </div>
          <div class="carousel-item">
            <!--<img src="<%=image_tag 'tenis.jpeg'%>" height=300px alt="Tenis image">-->
            <%=image_tag "tenis.jpeg", class: "d-block w-100"%>
          </div>
          <div class="carousel-item">
            <!--<img src="<%=image_tag 'archery.jpeg' %>" height=300px alt="Archery image">-->
            <%=image_tag "archery.jpeg", class: "d-block w-100"%>
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
         <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
      <nav class="nav nav-pills nav-fill container">
        <div class="text-center">
          <i class="fa-solid fa-bicycle mt-3"></i>
          <a class="nav-link">
           <%= link_to "Cycling", products_path, class: "nav-link mt-0" %>
          </a>
        </div>
        <div class="text-center">
          <i class="fa-solid fa-volleyball mt-3"></i>
          <a class="nav-link disable">
            <%= link_to "Voley", products_path, class: "nav-link mt-0" %>
          </a>
        </div>
        <div class="text-center">
          <i class="fa-solid fa-person-hiking mt-3"></i>
          <a class="nav-link disable">
            <%= link_to "Hiking", products_path, class: "nav-link mt-0" %>
          </a>
        </div>
        <div class="text-center">
          <i class="fa-solid fa-table-tennis-paddle-ball mt-3"></i>
          <a class="nav-link disabled">
            <%= link_to "Tenis", products_path, class: "nav-link mt-0" %>
          </a>
        </div>
        <div class="text-center">
          <i class="fa-solid fa-person-skiing mt-3"></i>
          <a class="nav-link disabled">
            <%= link_to "Skiing", products_path, class: "nav-link mt-0" %>
          </a>
        </div>
        <div class="text-center">
          <i class="fa-solid fa-basketball mt-3"></i>
          <a class="nav-link disabled">
           <%= link_to "Basketball", products_path, class: "nav-link mt-0" %>
          </a>
        </div>
        <div class="text-center">
          <i class="fa-solid fa-golf-ball-tee mt-3"></i>
          <a class="nav-link disabled">
            <%= link_to "Golf", products_path, class: "nav-link mt-0" %>
          </a>
        </div>
        <div class="text-center">
          <i class="fa-solid fa-table-tennis-paddle-ball mt-3"></i>
          <a class="nav-link disabled">
            <%= link_to "Baseball", products_path, class: "nav-link mt-0" %>
          </a>
        </div>
      </nav>
      <div class="footer">
        <div class="footer-links">
          <a href="#"><i class="fab fa-github"></i></a>
          <a href="#"><i class="fab fa-instagram"></i></a>
          <a href="#"><i class="fab fa-facebook"></i></a>
          <a href="#"><i class="fab fa-twitter"></i></a>
          <a href="#"><i class="fab fa-linkedin"></i></a>
        </div>
        <div class="footer-copyright">
          Airbnbsport <i class="fas fa-heart"></i>
        </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<div class="card-product">
<%= simple_form_for(@product) do |f| %>
  <img src="" />
  <div class="card-product-infos">
    <%= f.input :name %>
    <p><%= f.input :sport_id %><strong><%= f.input :description %></strong> <%= f.input :price %>.</p>
  </div>
  <% end %>
</div>


<header>
    <div class="container-fluid align-items-center justify-content-center ">
      <div class="text-center text-black bg-white">
        <nav class="navbar bg-white fixed-top">
          <div class="container-fluid">
            <a class="navbar-brand" href="#">Products</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
              <div class="offcanvas-header">
                <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Sports</h5>
                <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
              </div>
                <div class="offcanvas-body">
              <% @sports.each do |sport| %>
                  <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                    <li class="nav-item dropdown">
                      <a class="nav-link" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <%= sport.name %>
                      </a>
                    </li>
              <% end %>
                </div>
            </div>
          </div>
        </nav>
      </div>
    </div>
</header>


<main>
  <div class="bg-success p-2 text-dark bg-opacity-25">
    <div class="d-flex align-content-stretch flex-wrap">
      <div class="row row-cols-1 row-cols-md-3 g-4 my-2 mx-2 py-2 px-2">
        <% @products.each do |product| %>
        <div class="col-12 lg-12">
          <div class="w-auto p-3" style="background-color: #eee;">
            <div class="card h-100 shadow p-3 mb-5 bg-body rounded">
              <img src="..." class="card-img-top rounded-2" alt="..">
              <div class="card-body">
                <h5 class="card-title"><%= link_to product.name, product_path(product), class: "nav-link" %></h5>
                <p class="card-text"><%= product.description %></p>
              </div>
              <div class="card-footer">
                <p><small><%= product.price %> $USD</small></p>
                <p><small class="text-muted">Contactar dueño: <%= User.find(product.user_id).email %></small></p>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

<!-- inicia el footer de la card -->

<div class="card text-center">
  <div class="card-header">
     Airbnbsport <i class="fas fa-heart danger"></i>
  </div>

      <div class="card-body">
        <h5 class="card-title">Special title treatment</h5>
        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
        <div class="mt-3 mx-4">
          <button type="button" class="btn btn-outline-success text-primary text-opacity-75"><%= link_to "Arrienda tu propio equipo!", new_product_path, class: "nav-link" %> </button>
        </div>
      </div>

    <div class="card-footer w-100">
      <div class="footer-links">
        <div class="mx-auto">
          <a href="#"><i class="fab fa-github"></i></a>
          <a href="#"><i class="fab fa-instagram"></i></a>
          <a href="#"><i class="fab fa-facebook"></i></a>
          <a href="#"><i class="fab fa-twitter"></i></a>
          <a href="#"><i class="fab fa-linkedin"></i></a>
        </div>
      </div>
    </div>
</div>


<!-- termina el footer de la card -->

app/views/products/index.html.erb
<!-- inicia el header de la card -->

<!-- termina el header de la card -->

<!-- inicia el main de la card -->

  <div class="bg-success p-2 text-dark bg-opacity-25">

    <div class="row">
      <% @products.each do |product| %>
      <div class="col-3 col-lg-3">
        <div class="card-trip">
          <% if product.photo.key.present? %>
          <%= cl_image_tag(product.photo.key) %>
          <% end %>
          <div class="card-trip-infos">
            <div>
              <h5 class="card-title"><%= link_to product.name, product_path(product), class: "nav-link" %></h5>
              <p class="card-text"><%= product.description %></p>
            </div>
              <p><small><%= product.price %> $USD</small></p>
              <p><small class="text-muted">Contactar dueño: <%= User.find(product.user_id).email %></small></p>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>


<!-- termina el main de la card -->

<!-- inicia el footer de la card -->


<div class="card text-center">
  <div class="card-header">
     Airbnbsport <i class="fas fa-heart danger"></i>
  </div>

      <div class="card-body">
        <h5 class="card-title">Special title treatment</h5>
        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
        <div class="mt-3 mx-4">
          <button type="button" class="btn btn-outline-success "><%= link_to "Arrienda tu propio equipo!", new_product_path, class: "nav-link" %> </button>
        </div>
      </div>

    <div class="card-footer text-center ">
      <div class="footer-links">
        <div class="mx-auto">
          <a href="#"><i class="fab fa-github"></i></a>
          <a href="#"><i class="fab fa-instagram"></i></a>
          <a href="#"><i class="fab fa-facebook"></i></a>
          <a href="#"><i class="fab fa-twitter"></i></a>
          <a href="#"><i class="fab fa-linkedin"></i></a>
        </div>
      </div>
    </div>
</div>


<!-- termina el footer de la card -->

app/views/products/new.html.erb
<div class="bg-success p-2 text-dark bg-opacity-25">
  <div class="container">
        <div class= >
          <%= simple_form_for(@product) do |f| %>
          <%= f.input :name %>
          <%= f.input :description %>
          <%= f.input :price %>
          <%= f.association :sport %>
          <%= f.input :photo, as: :file %>
          <%= f.submit 'Create', class: 'btn btn-primary' %>
          <%end%>
        </div>
  </div>
</div>


<div class="card text-center">
  <div class="card-header">
     Airbnbsport <i class="fas fa-heart danger"></i>
  </div>

      <div class="card-body">
        <h5 class="card-title">Special title treatment</h5>
        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
        <div class="mt-3 mx-4">
          <button type="button" class="btn btn-outline-success text-primary text-opacity-75"><%= link_to "Arrienda tu propio equipo!", new_product_path, class: "nav-link" %> </button>
        </div>
      </div>


    <div class="card-footer w-100">
      <div class="footer-links">
        <div class="mx-auto">
          <a href="#"><i class="fab fa-github"></i></a>
          <a href="#"><i class="fab fa-instagram"></i></a>
          <a href="#"><i class="fab fa-facebook"></i></a>
          <a href="#"><i class="fab fa-twitter"></i></a>
          <a href="#"><i class="fab fa-linkedin"></i></a>
        </div>
      </div>
    </div>
</div>


<!-- termina el footer de la card -->

app/views/products/show.html.erb
<div>
  <div class="card text-center d-flex align-items-center">
      <div class="card-header">
        Catalog
      </div>
<!-- foto del producto -->
      <div class="d-flex align-items-center col-12 lg-12 bg-success p-2 text-dark bg-opacity-25">
        <div class= "card shadow p-3 mb-5 bg-body col-8 lg-6 m-3 y-3">
          <%= cl_image_tag(@product.photo.key, crop: :fill, height: 500) %>
        </div>
<!--card de la izquirda-->
        <div class="d-flex align-items-center bg-body card col-2 container lg-2 p-3 shadow my-5">
          <p class="card-text"><%= @product.name %></p>
          <p class="card-text"><%= @product.description%></p>
          <p class="card-text"><%= @product.price %> USD / día</p>
          <p><button type="button" class="btn btn-outline-success rounded-pill"><%= link_to "Arrendar!", new_product_booking_path(@product), class: "nav-link" %></button></p>
        </div>
      </div>


<!--Mapa  -->
  <div class="col-12 d-flex text-center lg-12 bg-success p-2 text-dark bg-opacity-25">
        <div class= "card shadow p-3 mb-5 bg-body col-8 lg-6 m-3 y-3">
          <div style="width: 100%; height: 600px;" data-controller="map" data-map-marker-value="<%= @marker.to_json %>" data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">

          </div>
        </div>
  </div>
</div>

<!-- inicia el footer de la card -->

<div class="card text-center">
  <div class="card-header">
     Airbnbsport <i class="fas fa-heart danger"></i>
  </div>

      <div class="card-body">
        <h5 class="card-title">Special title treatment</h5>
        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
        <div class="mt-3 mx-4">
          <button type="button" class="btn btn-outline-success text-primary text-opacity-75"><%= link_to "Arrienda tu propio equipo!", new_product_path, class: "nav-link" %> </button>
        </div>
      </div>

    <div class="card-footer w-100">
      <div class="footer-links">
        <div class="mx-auto">
          <a href="#"><i class="fab fa-github"></i></a>
          <a href="#"><i class="fab fa-instagram"></i></a>
          <a href="#"><i class="fab fa-facebook"></i></a>
          <a href="#"><i class="fab fa-twitter"></i></a>
          <a href="#"><i class="fab fa-linkedin"></i></a>
        </div>
      </div>
    </div>
</div>

<!-- termina el footer de la card -->

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://cdn-icons-png.flaticon.com/512/857/857418.png" %>
    <% end %>
      <div class='mx-5 w-50'>
        <div class='container py-3'>
          <div>
            <%= form_with url: products_path, class: 'd-flex', method: :get do %>
              <%= text_field_tag :query, params[:query], class: 'form-control', placeholder: '¿Qué producto buscas?' %>
              <%= submit_tag 'Buscar', class: 'btn btn-outline-search' %>
            <% end %>
          </div>
        </div>
      </div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Productos",products_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Reservas",bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Deportes",sports_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Edit acount", edit_user_password_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/sports/index.html.erb
<% @sports.each do |sport| %>
  <% if sport.name == "Trekking" %>
    <div class="card-category my-0" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.pexels.com/photos/3669288/pexels-photo-3669288.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2)">
     <%=sport.name  %>
    </div>
  <% elsif sport.name == "Tenis" %>
    <div class="card-category my-0" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.pexels.com/photos/5739125/pexels-photo-5739125.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2)">
     <%=sport.name  %>
    </div>
  <% elsif sport.name == "Futbol" %>
    <div class="card-category my-0" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.pexels.com/photos/2610960/pexels-photo-2610960.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2)">
     <%=sport.name  %>
    </div>
  <% elsif sport.name == "Basquetball" %>
    <div class="card-category my-0" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.pexels.com/photos/6763762/pexels-photo-6763762.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2)">
     <%=sport.name  %>
    </div>
  <% end %>
<% end %>

app/views/sports/new.html.erb
<h1>New sport</h1>
<%= simple_form_for(@sport) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit 'Add sport', class: 'btn btn-primary' %>
<% end %>